name: Docker Image CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bikedataproject/go-strava-daemon:staging
    - name: Login to GitHub Packages with Docker
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u anywaysopen --password-stdin
    - name: Publish the image.
      run: docker push bikedataproject/go-strava-daemon:staging
